Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/NegatedIf:
  Enabled: false